# Generated by Django 3.0.7 on 2020-07-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Command title')),
                ('command', models.CharField(max_length=2000, verbose_name='command')),
                ('describe', models.CharField(max_length=300, verbose_name='Command description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'command',
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.CharField(max_length=300, verbose_name='Recipient')),
                ('title', models.CharField(max_length=2000, verbose_name='Mail title')),
                ('content', models.TextField(verbose_name='Email Content')),
                ('send_result', models.BooleanField(default=False, verbose_name='Result')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email log',
                'ordering': ['-created_time'],
            },
        ),
    ]
